version: '3.8'
services:
  cert-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./certs:/certs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped