services:
  cert-manager:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./certs:/certs
      - ./config:/config
      - ./logs:/logs
      - ./dummyParent:/dummyParent
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
      - "4443:4443"
    environment:
      - CONFIG_DIR=/config
      - CERT_MANAGER_CERT_PATH=/certs
      - VSCODE_DISABLE_CACHE=true
      - DOCKER_HOST_OS=windows
      #- DISABLE_AUTH=true
      #- DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-}
    restart: unless-stopped
    dns:
      - 192.168.178.252
      - 192.168.178.251
    #user: "${UID:-1000}:${GID:-1000}"